# Generated by Django 4.1 on 2023-05-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('auditor_lider', models.CharField(max_length=50, verbose_name='Auditor Líder')),
                ('otros_auditores', models.CharField(blank=True, max_length=50, null=True, verbose_name='Otros Auditores')),
                ('representante_cliente', models.CharField(max_length=150, verbose_name='Representantes del Cliente Auditado')),
                ('alcance', models.CharField(max_length=500, verbose_name='Alcance')),
                ('criterio', models.CharField(max_length=500, verbose_name='Criterio')),
                ('objetivo', models.CharField(max_length=500, verbose_name='Objetivo')),
                ('estado', models.BooleanField(default=False, verbose_name='Auditoría Finalizada')),
                ('created_add', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio de auditoría')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
