# Generated by Django 4.1 on 2023-05-07 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia', models.CharField(max_length=500, verbose_name='Edidencia Objetiva')),
                ('ampliar_evidencia', models.TextField(verbose_name='Ampliar evidencia')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditoria')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ['-evidencia'],
            },
        ),
        migrations.CreateModel(
            name='No_conforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='No Conformidad')),
                ('criterio_evidencia', models.CharField(max_length=100, verbose_name='Criterio')),
                ('nc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.evidencia')),
            ],
            options={
                'verbose_name': 'No Conformidad',
                'verbose_name_plural': 'No Conformidades',
                'ordering': ['-texto'],
            },
        ),
    ]
