# Generated by Django 4.1 on 2023-05-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=50, unique=True, verbose_name='Razón Social')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('rubro', models.IntegerField(choices=[(1, 'Lacteos')], default=1, verbose_name='Rubro')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('persona_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de contacto')),
                ('celular_contacto', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular de contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio de contrato')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
            },
        ),
    ]
